name: Publish manylinux_x86_64 image
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
    - dockerfiles/manylinux_x86_64.Dockerfile
    - .github/workflows/publish_manylinux_x86_64.yml

jobs:
  build-and-push-image:
    uses: ./.github/workflows/publish_dockerfile.yml
    with:
        DOCKERFILE_NAME: manylinux_x86_64
        PLATFORMS: linux/amd64
