name: Publish cpubuilder images
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
    - dockerfiles/cpubuilder_ubuntu_jammy*.Dockerfile
    - .github/workflows/publish_cpubuilder.yml

permissions:
  contents: read
  packages: write

jobs:
  build-cpubuilder-ubuntu-jammy:
    uses: ./.github/workflows/publish_dockerfile.yml
    with:
        DOCKERFILE_NAME: cpubuilder_ubuntu_jammy
        PLATFORMS: linux/amd64,linux/arm64

  build-cpubuilder-ubuntu-jammy-ghr:
    uses: ./.github/workflows/publish_dockerfile.yml
    with:
        DOCKERFILE_NAME: cpubuilder_ubuntu_jammy_ghr
        PLATFORMS: linux/amd64,linux/arm64
