name: Publish amdgpu x86_64 images
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
    - dockerfiles/amdgpu*_x86_64.Dockerfile
    - .github/workflows/publish_amdgpu_x86_64.yml

permissions:
  contents: read
  packages: write

jobs:
  build-amdgpu-ubuntu-jammy:
    uses: ./.github/workflows/publish_dockerfile.yml
    with:
        DOCKERFILE_NAME: amdgpu_ubuntu_jammy_x86_64
        PLATFORMS: linux/amd64

  build-amdgpu-ubuntu-jammy-ghr:
    uses: ./.github/workflows/publish_dockerfile.yml
    with:
        DOCKERFILE_NAME: amdgpu_ubuntu_jammy_ghr_x86_64
        PLATFORMS: linux/amd64
